### ISSUE TITLE
OnClick event is not firing

### ISSUE THREAD

**Issue by last-Programmer** [react-grid-layout/react-grid-layout#2092]
### Describe the bug

When i attach onlick event to grid item it is not firing on onclick.

This was working with version 1.4.2. From version 1.4.3 on wards it is not working. Please see the attached sand box.

### Your Example Website or App

https://codesandbox.io/p/sandbox/zealous-platform-jffkrw

### Steps to Reproduce the Bug or Issue

Go to the attachd sand box and click on a item and you can see that the click event is not firing. 

### Expected behavior

When the user clicks the item a messagebox has to be displayed but it is not firing the click event on the grid item.

### react-grid-layout library version

1.5.0

### Operating System Version

Windows

### Browser

Chrome

**Comment by last-Programmer** [comment]
As a workaround i did this

```
        /* Need to simulate click event using mousedown and mouseup because of this issue
        * https://github.com/react-grid-layout/react-grid-layout/issues/166
        * We cant use draggableCancel because we need both dragging and clicking on quick menu item
        */
        const handleMouseDown = (event: MouseEvent): void => {
            refPos.current = { x: event.clientX, y: event.clientY };
        };

        const handleMouseUp = (event: MouseEvent): void => {
            if (event.button === 0) {
                if (Math.abs(event.clientX - refPos.current.x) < 4
                    && Math.abs(event.clientY - refPos.current.y) < 4) {
                    handleClick(event);
                }
            }
        };
```

**Comment by last-Programmer** [comment]
@l-bianchi how does it was working with version 14.2 i need both click and drag should work grid item.. we are displaying menus as tiles and let the user rearrange the items by drag and drop. and also when clicks on the item we navigate to different page. Is there not a way to make both drag & click works on whold grid item as in 1.4.2. thanks

**Comment by l-bianchi** [comment]
I had an issue similar to yours where my buttons in the draggable item where not clickable because of the drag event and i fixed it by setting the buttons area as draggableCancel. If you need the whole area to be clickable I imagine it to be a bigger issue because you need to discriminate between the drag start and the click. Maybe in the onDragStart event you can implement some custom logic to recognize the click.
If that is not possible I would suggest a rollback to a version where it was working. Good luck!

**Comment by last-Programmer** [comment]
i have already solved via hacking drag events ondragstart, ondrag and ondragend. since it was working with 1.4.2 i was wondering why the behaviour is changed with new version.

**Comment by francho-plain** [comment]
Same here. I roll back to 1.4.2 because I need both (click&drag) in my dashboard widgets. 
An option to configure this could be great.

@last-Programmer: can you paste your custom events?

**Comment by dinesh-gamage** [comment]
I also encountered this issue after upgrading to React 18 and updating **react-grid-layout** from **1.4.2** to **1.5.0**. I struggled with it for a few days until I found the cause.  

It seems that in the new version, the placeholder (`.react-grid-placeholder`) is added to the DOM on the **mousedown** event, whereas in the previous version, it was added on **drag start**.  

(Note: I haven’t reviewed the source code of **react-grid-layout**; this is based on my observations while troubleshooting.)  

While [[this PR](https://github.com/react-grid-layout/react-grid-layout/pull/2108/files)](https://github.com/react-grid-layout/react-grid-layout/pull/2108/files) is a hack to get the click event working, this needs to be properly fixed at the source code level.

**Comment by Thomas101** [comment]
[The PR](https://github.com/react-grid-layout/react-grid-layout/pull/2108/files) also fixes https://github.com/react-grid-layout/react-grid-layout/issues/1980

**Comment by gyyy2020** [comment]
It still not fixed yet, I use 1.5.2 version, I have tortured ai for days.

**Comment by rawbin-** [comment]
> It still not fixed yet, I use 1.5.2 version, I have tortured ai for days.

same problem

**Comment by STRML** [comment]
This is fixed in v2.2.0! The new `dragConfig.threshold` option prevents drag detection from intercepting clicks.

In v2, the default threshold is 3px - clicks without movement pass through normally:

```jsx
// v2 API - clicks work, drags require 3px movement
<GridLayout dragConfig={{ threshold: 3 }} ... />
```

Please upgrade to v2.2.0+ where onClick events fire correctly.

**Comment by last-Programmer** [comment]
@STRML Thank you for the fix. Click event is firing. but we have a problem where there is a drag operation click event should not fire. Click event always fires even when dragging or completion of dragging. So to get it work we need to keep track of dragging with onDrag event. Would be nicer if the click event does not fire on drag start
